### ISSUE TITLE
Just a little more documentation on output files?

### ISSUE THREAD

**Issue by AndydeCleyre** [Valarissa/easy_log4r#1]
Hi,

Thanks for this gem!

I am trying to use this as a simple way to get our app logging errors to their own file. This seems an ideal choice, because the readme states that basic usage

> gives you two default outputs, one to stdout for all levels of logging, and one to stderr for the error and fatal levels of logging.

So I modified every class or file that called Rails' `logger`, added 

``` ruby
include EasyLog4r::EasyLogger
```

and changed `logger` calls to `log4r` calls.

It is not clear where any of the new logs are supposed to go. I expected them in the app's `log` directory, but there seems to be no change in file listing there, and all non-explicitly-logged errors are showing up in `production.log`, while the `log4r.error` and `log4r.info` items are not.

Could you add a little more documentation with information such as where to find the separated error log?

I am using `rails` 3.2.17 .

**Comment by Valarissa** [comment]
Hey there, so, this gem is effectively a simplification of the Log4r gem and logging standards set forth by that. Effectively, what's happening now are the standard outputs, in this case, StdErr and StdOut as the defaults. These are the standard unix outputs so they should only output to a file if you pipe the outputs of the rails server when you first start the instance... Something like `rails s &1> log/stdout.log &2> log/stderr.log`

That's not the best way to go about doing this though. What you're probably looking for is to define your own outputter(s). You can set one up to be the default, so that if you don't define any others, it simply uses an instance of the default one defined. You can find a brief overview on how to do that here: https://github.com/Valarissa/easy_log4r/wiki/Log4r-Yaml-Configuration

Based on what you talked about you'll probably want to create a DateFileOutputter: http://log4r.rubyforge.org/rdoc/Log4r/DateFileOutputter.html or a FileOutputter: http://log4r.rubyforge.org/rdoc/Log4r/FileOutputter.html either way, you'll probably want to find out more about outputters in general, which you can find here: http://log4r.rubyforge.org/rdoc/Log4r/rdoc/outputter.html

Hopefully that helps, if you need any more help in getting things started, let me know and I'll be happy to help. :)

**Comment by AndydeCleyre** [comment]
Thanks, this is very helpful!
